# This file contains default configuration.
#
# Additional config files:
#   Development: appsettings.Development.yml
#   Production:  appsettings.Production.yml
#   Kubernetes:  values.yaml + helmfile.yaml
#   Local IDE:   launchSettings.json

Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning # Reduce ASP.NET Core verbosity

Authentication:
  Realm: myvendor-servicebroker

Broker:
  Catalog:
    Services:
      - Id: myservice1
        Name: myservice1
        Description: A service.
        Plans:
          - Id: myplan1a
            Name: myplan1a
            Description: A plan.
          - Id: myplan1b
            Name: myplan1b
            Description: A plan.
      - Id: myservice2
        Name: myservice2
        Description: A service.
        Plans:
          - Id: myplan2a
            Name: myplan2a
            Description: A plan.
          - Id: myplan2b
            Name: myplan2b
            Description: A plan.
